/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.espoch.jalec.vista;

import ec.edu.espoch.jalec.vista.Configuracion;
import javax.swing.JOptionPane;



/**
 *
 * @author anthony
 */
public class Configuracion extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarTarea
     */
    public Configuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTexto = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblMoneda = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtTexto1 = new javax.swing.JTextField();
        jbAgregarT = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtTexto2 = new javax.swing.JComboBox<>();
        txtTexto3 = new javax.swing.JComboBox<>();
        SAlir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Tarea");

        lblTexto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTexto.setText("Configuracion");

        lblId.setText("Nombre de la Tienda");

        lblMoneda.setText("Moneda:");

        lblDescripcion.setText("Unidad de Medida:");

        txtTexto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTexto1ActionPerformed(evt);
            }
        });

        jbAgregarT.setText("Soporte/Ayuda");
        jbAgregarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarTActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Cerrar Seccion");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTexto2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtTexto2.setToolTipText("");
        txtTexto2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtTexto2ItemStateChanged(evt);
            }
        });

        txtTexto3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SAlir.setText("Salir");
        SAlir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAlirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jbLimpiar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblId)
                                .addComponent(lblMoneda, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SAlir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbAgregarT))
                            .addComponent(txtTexto3, javax.swing.GroupLayout.Alignment.LEADING, 0, 231, Short.MAX_VALUE)
                            .addComponent(txtTexto2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTexto)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoneda)
                    .addComponent(txtTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtTexto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarT)
                    .addComponent(jbLimpiar)
                    .addComponent(SAlir))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTexto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTexto1ActionPerformed

    private void jbAgregarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarTActionPerformed
      //Controlador.agregarControlador();
    Soporte soporteVentana = new Soporte(); 
    soporteVentana.setVisible(true);        
    soporteVentana.setLocationRelativeTo(null); 
    }//GEN-LAST:event_jbAgregarTActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTexto2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtTexto2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTexto2ItemStateChanged

    private void SAlirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAlirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea salir de la aplicación?", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        
         
    }//GEN-LAST:event_SAlirActionPerformed
    public void salir(){
    
    txtTexto1.setText("");
    
    }
    public void guardar(){
        txtTexto1.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAlir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbAgregarT;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JTextField txtTexto1;
    private javax.swing.JComboBox<String> txtTexto2;
    private javax.swing.JComboBox<String> txtTexto3;
    // End of variables declaration//GEN-END:variables


  

}
